name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: submodules-init
        uses: snickerbockers/submodules-init@v4
      - name: Build with Maven
        run: mvn -B package -T 2C
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: MC2TG
          path: target/MC2TG-0.1.0.jar
